FROM python:3.7.6

WORKDIR /work

ARG ARG_LINE_CHANNEL_ACCESS_TOKEN 
ARG ARG_LINE_CHANNEL_SECRET

ENV LINE_CHANNEL_ACCESS_TOKEN=${ARG_LINE_CHANNEL_ACCESS_TOKEN} LINE_CHANNEL_SECRET=${ARG_LINE_CHANNEL_SECRET}

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

COPY /app ./

CMD [ "python", "./app.py" ]